# Empty conf file - mapped in Makefile.def
# This file is only used when compiling with MILE,
# a UofM-developed ionospheric electrodynamics library

# Electrodynamics specific compiler workarounds

# 1. Clear debug flags if DEBUG is not TRUE
ifneq ($(DEBUG),TRUE)
  DBGFLAGS := 
endif

# 2. Prevent cascade promotion of double precision to REAL(16)
#    We do this by replacing -fdefault-real-8 with -freal-4-real-8
FFLAGS := $(subst -fdefault-real-8,-freal-4-real-8,$(FFLAGS))

# 3. Re-evaluate Cflag3 so the above overrides take effect
Cflag3 = $(CFLAG) $(FFLAGS) $(OPTIM) $(DBGFLAGS)
